name: cypress tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
        ports:
          - 8001:8002
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup
        run: |
          docker-compose -v
          docker-compose up -d

      - name: Run Cypresss Tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          wait-on: http://localhost:8002
          wait-on-timeout: 60

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: cypress/reports

      - name: Teardown
        run: |
          docker-compose down