name: cypress tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
        ports:
          - 8001:8002
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup
        run: |
          docker-compose -v
          docker-compose up -d

      - name: Wait for the services to be up
        run: |
          while ! curl -sSf http://localhost:8002/ > /dev/null; do
            echo "Waiting for service at http://localhost:8002 to be up..."
            sleep 5
          done

      - name: Run Cypress Tests
        run: npm run clean:reports && npm run cy:run

      - name: Generate Report
        run: npm run report:merge && npm run report:generate

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: cypress/reports/report.html

      - name: Teardown
        run: |
          docker-compose down